# K3S_VERSION=1.33.0
# K3S_TOKEN=${RANDOM}${RANDOM}${RANDOM} docker-compose up

services:

  server:
    image: "rancher/k3s:v1.33.0-k3s1"
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443  # Kubernetes API Server
    - "127.0.0.1:8080:80"    # Ingress controller port 80 -> host port 8080
    - "127.0.0.1:443:443"    # Ingress controller port 443 (localhost only)

  agent:
    image: "rancher/k3s:v1.33.0-k3s1"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}
    volumes:
    - k3s-agent:/var/lib/rancher/k3s

  agent2:
    image: "rancher/k3s:v1.33.0-k3s1"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}
    volumes:
    - k3s-agent2:/var/lib/rancher/k3s

volumes:
  k3s-server: {}
  k3s-agent: {}

  k3s-agent2: {}
